name: krwv-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - networkx
  - pydot
  - openpyxl
  - hiplot
  - shap
  - xgboost
  - lightgbm
  - imbalanced-learn
  - category_encoders
  - packaging
  - causal-learn
  - mapie
  - pillow
  - streamlit
  - sklearn-quantile
  - tk
  - pip
  - pip:
      - git+https://github.com/deanbodenham/momentchi2py.git  # dependency of causl-learn; otherwise version error (2025/02/03)
